#!/bin/bash

watchdir=${1-.}
shift;
cmd="${@}"
if [[ -z $cmd ]]; then
    cmd="node $(find -name server.js)"
fi
pidfile=$(tempfile -p makemon)
trap "rm $pidfile" EXIT

while true; do
    if make; then
        $cmd &
        echo $! > $pidfile
    fi
    inotifywait -r -q -e modify "$watchdir"
    kill $(<$pidfile) >/dev/null 2>&1
done  
